# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='data',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тип тренировки'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Training', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
