# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20180402_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ('data', 'id'), 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
    ]
