# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 00:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
