# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180402_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
