# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180402_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
