# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20180402_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default='nothing', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
